### ISSUE TITLE
How's it going?

### ISSUE THREAD

**Issue by rstacruz** [compleatang/legal-markdown#32]
I see the readme has this notice:

> DEPRECATED. This repository is no longer maintained. Please fork and work away.

Can I ask what led to its deprecation? Have you found a better solution?

**Comment by compleatang** [comment]
Depreciation notice mostly due to lack of time. Haven't really looked for something on point and better.

**Comment by rstacruz** [comment]
I take it you're back to using Word? :-)

**Comment by compleatang** [comment]
Oh God no! I'm doing pure legal tech now :) 

 https://erisindustries.com
